import { useCallback, useRef, useState } from 'react';
import { createPortal } from 'react-dom';

import {
  AlertTriangle,
  Copy,
  Download,
  ExternalLink,
  FileText,
  Sparkles,
  X,
  ZoomIn,
} from 'lucide-react';

import { HtmlSandbox, MarkdownArtifact } from '@/components/artifacts/live';
import { MARKDOWN_EXTS, extOf } from '@/components/shared/ChatInput.types';
import { API_BASE_URL } from '@/config';
import type { MediaProvenanceInfo } from '@/shared/lib/provenance';
import { useLanguage } from '@/shared/providers/language-provider';

// ── Provenance badge ─────────────────────────────────────────────────────────

/**
 * Small pill surfaced on every AI-generated media asset.
 *
 * Shows "generated by {provider} · {model}" by default. When the actual
 * provider/model differs from what the user requested (silent fallback in
 * the router), the pill switches to a distinct "fallback used" style with
 * the reason in the tooltip. This is the perceptible disclosure required
 * by the EU AI Act Art. 50 and recommended by the IAB Disclosure Framework.
 */
const BADGE_BASE =
  'inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium backdrop-blur-sm';
const BADGE_POSITIONED_OVERLAY =
  'pointer-events-auto absolute bottom-2 left-2 z-10';

function pickBadgeTone(isFallback: boolean, isOverlay: boolean): string {
  if (isFallback) return 'bg-amber-500/90 text-white';
  if (isOverlay) return 'bg-black/60 text-white';
  return 'bg-muted text-foreground/80';
}

function isProviderMismatch(
  provider: string | undefined,
  requestedProvider: string | undefined,
): boolean {
  if (!provider || !requestedProvider) return false;
  const p = provider.toLowerCase();
  const r = requestedProvider.toLowerCase();
  return !p.includes(r) && !r.includes(p);
}

export function MediaProvenanceBadge({
  provenance,
  variant = 'overlay',
}: {
  provenance: MediaProvenanceInfo | undefined;
  /** `overlay` floats on top of the media; `inline` sits in the toolbar row */
  variant?: 'overlay' | 'inline';
}) {
  const { t, tt } = useLanguage();
  if (!provenance) return null;
  const { provider, model, requestedProvider, fallbackReason } = provenance;
  if (!provider && !model) return null;

  const isFallback =
    !!fallbackReason || isProviderMismatch(provider, requestedProvider);

  const displayLabel = provider
    ? tt('task.provenanceGeneratedBy', { provider })
    : t.task.provenanceAiGenerated;
  const label = model ? `${displayLabel} · ${model}` : displayLabel;

  const tooltipLines = [label];
  if (isFallback && requestedProvider) {
    tooltipLines.push(
      tt('task.provenanceRequestedWas', { provider: requestedProvider }),
    );
  }
  if (fallbackReason) {
    tooltipLines.push(
      tt('task.provenanceFallbackReason', { reason: fallbackReason }),
    );
  }

  const isOverlay = variant === 'overlay';
  const tone = pickBadgeTone(isFallback, isOverlay);
  const positioned = isOverlay ? BADGE_POSITIONED_OVERLAY : '';
  const text = isFallback
    ? `${t.task.provenanceFallbackUsed} · ${label}`
    : label;
  const Icon = isFallback ? AlertTriangle : Sparkles;

  return (
    <span
      className={`${BADGE_BASE} ${positioned} ${tone}`}
      title={tooltipLines.join('\n')}
      aria-label={tooltipLines.join('. ')}
    >
      <Icon size={10} aria-hidden />
      <span className="max-w-[220px] truncate">{text}</span>
    </span>
  );
}

// ── Lightbox overlay ─────────────────────────────────────────────────────────

export type LightboxType = 'image' | 'video' | 'audio' | 'pdf' | 'text';

export function MediaLightbox({
  src,
  alt,
  type,
  textContent,
  textLanguage,
  provenance,
  onClose,
}: {
  /** For image/video/audio/pdf: an accessible URL. For text: unused. */
  src: string;
  alt?: string;
  type: LightboxType;
  /** Pre-loaded file content for type='text'. When present, rendered verbatim. */
  textContent?: string;
  /** Hint for syntax category; currently only used to pick monospace vs markdown styling. */
  textLanguage?: 'markdown' | 'code' | 'plain' | 'html' | 'svg';
  provenance?: MediaProvenanceInfo;
  onClose: () => void;
}) {
  const { t } = useLanguage();

  const handleDownload = useCallback(async () => {
    const filename = alt || src.split('/').pop()?.split('?')[0] || 'download';

    try {
      const { save } = await import('@tauri-apps/plugin-dialog');
      const savePath = await save({ defaultPath: filename });
      if (!savePath) return;

      try {
        const { copyFile } = await import('@tauri-apps/plugin-fs');
        // src may be a streaming URL — extract the file path from the query
        const filePath = extractLocalPath(src);
        if (filePath) {
          await copyFile(filePath, savePath);
          return;
        }
      } catch {
        /* fall through to fetch-based download */
      }

      // Fetch the blob and write it
      const { writeFile } = await import('@tauri-apps/plugin-fs');
      const res = await fetch(src);
      const buf = new Uint8Array(await res.arrayBuffer());
      await writeFile(savePath, buf);
    } catch {
      // Browser fallback
      const a = document.createElement('a');
      a.href = src;
      a.download = filename;
      a.click();
    }
  }, [src, alt]);

  const handleCopy = useCallback(async () => {
    if (type !== 'image') return;
    try {
      const res = await fetch(src);
      const blob = await res.blob();
      await navigator.clipboard.write([
        new ClipboardItem({ [blob.type]: blob }),
      ]);
    } catch {
      /* clipboard write not supported */
    }
  }, [src, type]);

  const handleOpenExternal = useCallback(async () => {
    const filePath = extractLocalPath(src);
    if (filePath) {
      try {
        const { openPath } = await import('@tauri-apps/plugin-opener');
        await openPath(filePath);
        return;
      } catch {
        /* fall through */
      }
    }
    window.open(src, '_blank');
  }, [src]);

  return createPortal(
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/85"
      onClick={onClose}
    >
      {/* Provenance badge — anchored top-left so it never collides with the toolbar */}
      {provenance && (
        <div
          className="absolute top-4 left-4 z-10"
          onClick={(e) => e.stopPropagation()}
        >
          <MediaProvenanceBadge provenance={provenance} variant="inline" />
        </div>
      )}

      {/* Toolbar */}
      <div
        className="absolute top-4 right-4 z-10 flex items-center gap-1"
        onClick={(e) => e.stopPropagation()}
      >
        {type === 'image' && (
          <button
            className="rounded-full bg-white/10 p-2 text-white hover:bg-white/20"
            onClick={handleCopy}
            title={t.task.lightboxCopy}
          >
            <Copy size={16} />
          </button>
        )}
        <button
          className="rounded-full bg-white/10 p-2 text-white hover:bg-white/20"
          onClick={handleDownload}
          title={t.task.lightboxDownload}
        >
          <Download size={16} />
        </button>
        <button
          className="rounded-full bg-white/10 p-2 text-white hover:bg-white/20"
          onClick={handleOpenExternal}
          title={t.task.lightboxOpenExternal}
        >
          <ExternalLink size={16} />
        </button>
        <button
          className="rounded-full bg-white/10 p-2 text-white hover:bg-white/20"
          onClick={onClose}
          title={t.task.lightboxClose}
        >
          <X size={20} />
        </button>
      </div>

      {type === 'image' && (
        <img
          src={src}
          alt={alt}
          className="max-h-[90vh] max-w-[90vw] rounded-lg object-contain"
          onClick={(e) => e.stopPropagation()}
        />
      )}
      {type === 'video' && (
        <video
          src={src}
          controls
          autoPlay
          className="max-h-[90vh] max-w-[90vw] rounded-lg bg-black"
          onClick={(e) => e.stopPropagation()}
        />
      )}
      {type === 'audio' && (
        <div
          className="flex flex-col items-center gap-4 rounded-lg bg-white/5 p-6"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="font-medium text-white/80">{alt}</div>
          <audio src={src} controls className="w-[70vw] max-w-xl" />
        </div>
      )}
      {type === 'pdf' && (
        // Browser's native PDF viewer — works for both blob: and
        // /files/stream?path=… sources. We use <iframe> rather than <embed>
        // for consistent cross-platform controls.
        <iframe
          src={src}
          title={alt ?? 'PDF preview'}
          className="h-[90vh] w-[90vw] rounded-lg bg-white"
          onClick={(e) => e.stopPropagation()}
        />
      )}
      {type === 'text' && (
        <div
          className="bg-background max-h-[90vh] w-[min(90vw,960px)] overflow-auto rounded-lg shadow-xl"
          onClick={(e) => e.stopPropagation()}
        >
          {textLanguage === 'markdown' ? (
            <MarkdownArtifact source={textContent ?? ''} />
          ) : textLanguage === 'html' ? (
            <HtmlSandbox
              html={textContent ?? ''}
              identity={src || alt || 'lightbox'}
              title={alt}
            />
          ) : (
            <pre className="bg-neutral-900 p-4 font-mono text-xs whitespace-pre text-white">
              {textContent ?? ''}
            </pre>
          )}
        </div>
      )}
    </div>,
    document.body,
  );
}

// ── Inline chat image with click-to-zoom ─────────────────────────────────────

export function InlineChatImage({
  src,
  alt,
  provenance,
}: {
  src: string;
  alt?: string;
  provenance?: MediaProvenanceInfo;
}) {
  const { t } = useLanguage();
  const [open, setOpen] = useState(false);
  if (!src) return null;
  return (
    <>
      <div className="group/image relative my-3 inline-block">
        <img
          src={src}
          alt={alt}
          className="max-h-80 w-auto cursor-zoom-in rounded-lg object-contain"
          onClick={() => setOpen(true)}
          onError={(e) => {
            (e.currentTarget as HTMLImageElement).style.display = 'none';
          }}
          title={t.task.lightboxViewFull}
        />
        <MediaProvenanceBadge provenance={provenance} variant="overlay" />
      </div>
      {open && (
        <MediaLightbox
          src={src}
          alt={alt}
          type="image"
          provenance={provenance}
          onClose={() => setOpen(false)}
        />
      )}
    </>
  );
}

// ── Inline chat video with expand button ─────────────────────────────────────

export function InlineChatVideo({
  src,
  provenance,
}: {
  src: string;
  provenance?: MediaProvenanceInfo;
}) {
  const { t } = useLanguage();
  const [open, setOpen] = useState(false);
  if (!src) return null;
  return (
    <>
      <div className="group/video relative my-3 inline-block">
        <video
          src={src}
          controls
          className="max-h-80 w-auto rounded-lg"
          preload="metadata"
          onError={(e) => {
            (e.currentTarget as HTMLVideoElement).style.display = 'none';
          }}
        />
        <button
          className="absolute top-2 right-2 rounded-full bg-black/50 p-1.5 text-white opacity-0 transition-opacity group-hover/video:opacity-100"
          onClick={() => setOpen(true)}
          title={t.task.lightboxViewFull}
          aria-label={t.task.lightboxViewFull}
        >
          <ZoomIn size={14} />
        </button>
        <MediaProvenanceBadge provenance={provenance} variant="overlay" />
      </div>
      {open && (
        <MediaLightbox
          src={src}
          type="video"
          provenance={provenance}
          onClose={() => setOpen(false)}
        />
      )}
    </>
  );
}

// ── Inline chat PDF chip with click-to-preview ──────────────────────────────

/**
 * PDFs are heavy to render inline (every chip would spawn an iframe), so we
 * surface them as a compact clickable chip. Clicking opens the same lightbox
 * the attachment preview uses, which renders the browser-native PDF viewer.
 */
export function InlineChatPdf({
  src,
  name,
  provenance,
}: {
  src: string;
  name?: string;
  provenance?: MediaProvenanceInfo;
}) {
  const { t } = useLanguage();
  const [open, setOpen] = useState(false);
  if (!src) return null;
  const displayName = name ?? src.split('/').pop()?.split('?')[0] ?? 'PDF';
  return (
    <>
      <div className="my-3 inline-flex max-w-full items-center">
        <button
          type="button"
          onClick={() => setOpen(true)}
          className="border-border/60 bg-muted/40 hover:bg-muted/70 flex items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
          title={t.task.lightboxViewFull}
          aria-label={`${t.task.lightboxViewFull} — ${displayName}`}
        >
          <FileText className="text-muted-foreground size-4 shrink-0" />
          <span className="max-w-[260px] truncate">{displayName}</span>
          <MediaProvenanceBadge provenance={provenance} variant="inline" />
        </button>
      </div>
      {open && (
        <MediaLightbox
          src={src}
          alt={displayName}
          type="pdf"
          provenance={provenance}
          onClose={() => setOpen(false)}
        />
      )}
    </>
  );
}

// ── Inline chat document chip (markdown, code, text, json, csv, …) ─────────

/** 5 MB cap — keeps a rogue big log from freezing the webview on decode. */
const INLINE_DOC_MAX_BYTES = 5 * 1024 * 1024;

/**
 * Clickable chip for any text-previewable file (markdown / code / txt / json /
 * csv / yaml / …). Click lazy-loads the content via `POST /files/read` and
 * opens the shared lightbox in text mode.
 */
export function InlineChatDocument({
  path,
  name,
  provenance,
}: {
  path: string;
  name?: string;
  provenance?: MediaProvenanceInfo;
}) {
  const { t } = useLanguage();
  const [open, setOpen] = useState(false);
  const [content, setContent] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const loadingRef = useRef(false);
  const displayName = name ?? path.split('/').pop()?.split('?')[0] ?? 'file';
  const ext = extOf(displayName);
  const language: 'markdown' | 'code' | 'html' =
    ext === 'html' || ext === 'htm'
      ? 'html'
      : MARKDOWN_EXTS.has(ext)
        ? 'markdown'
        : 'code';

  const handleOpen = async () => {
    setOpen(true);
    if (content !== null || error !== null) return;
    if (loadingRef.current) return;
    loadingRef.current = true;
    try {
      const res = await fetch(`${API_BASE_URL}/files/read`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ path }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = (await res.json()) as { content?: string; error?: string };
      if (body.error) throw new Error(body.error);
      const raw = body.content ?? '';
      if (raw.length > INLINE_DOC_MAX_BYTES) {
        setError(
          `File too large to preview (${Math.round(raw.length / 1024 / 1024)} MB). Open it externally instead.`,
        );
      } else {
        setContent(raw);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load preview');
    } finally {
      loadingRef.current = false;
    }
  };

  if (!path) return null;
  return (
    <>
      <div className="my-3 inline-flex max-w-full items-center">
        <button
          type="button"
          onClick={handleOpen}
          className="border-border/60 bg-muted/40 hover:bg-muted/70 flex items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors"
          title={t.task.lightboxViewFull}
          aria-label={`${t.task.lightboxViewFull} — ${displayName}`}
        >
          <FileText className="text-muted-foreground size-4 shrink-0" />
          <span className="max-w-[260px] truncate">{displayName}</span>
          <MediaProvenanceBadge provenance={provenance} variant="inline" />
        </button>
      </div>
      {open && (content !== null || error !== null) && (
        <MediaLightbox
          src=""
          alt={displayName}
          type="text"
          textContent={error ?? content ?? ''}
          textLanguage={language}
          provenance={provenance}
          onClose={() => setOpen(false)}
        />
      )}
    </>
  );
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Extract local file path from a /files/stream?path=... URL. */
function extractLocalPath(url: string): string | null {
  try {
    if (url.includes('/files/stream?path=')) {
      const u = new URL(url, 'http://localhost');
      return u.searchParams.get('path');
    }
  } catch {
    /* not a valid URL */
  }
  return null;
}
