import type { MediaDataEgress } from '@/shared/media/data-egress';
import type { ProviderId } from '@/shared/video/types';

export interface ProviderCapability {
  id: ProviderId;
  label: string;
  kinds: Array<
    | 'image'
    | 't2v'
    | 'i2v'
    | 'lipsync'
    | 'voice'
    | 'music'
    | 'broll'
    | 'transcribe'
    | 'video-analysis'
  >;
  status: 'active' | 'preview' | 'account-gated' | 'deprecated' | 'disabled';
  requiresApiKey: boolean;
  dataEgress: MediaDataEgress;
  defaultCostPerSecCents?: number;
  maxClipSec: number;
  resolutions: string[];
  supportsAudio: boolean;
  license: 'commercial-ok' | 'commercial-with-permission' | 'non-commercial';
  sourceUrl: string;
  lastVerifiedAt: string;
  shutdownAt?: string;
  probeRequired: boolean;
  notes?: string;
}

export const LEGACY_SORA_PROVIDER_IDS = [
  'sora-2',
  'sora-2-pro',
  'sora-2025-02-01',
] as const;

export const VIDEO_PROVIDER_CAPABILITIES: ProviderCapability[] = [
  {
    id: 'seedream-5-0',
    label: 'BytePlus Seedream 5.0',
    kinds: ['image'],
    status: 'active',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: ['2K', '4K'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://www.volcengine.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'seedream-5-0-lite',
    label: 'BytePlus Seedream 5.0 Lite',
    kinds: ['image'],
    status: 'active',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: ['2K'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://www.volcengine.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'seedream-4-5',
    label: 'BytePlus Seedream 4.5',
    kinds: ['image'],
    status: 'disabled',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: ['2K'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://www.volcengine.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'veo-3-1-generate',
    label: 'Google Veo 3.1',
    kinds: ['t2v', 'i2v'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 50,
    maxClipSec: 8,
    resolutions: ['720p', '1080p'],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://cloud.google.com/vertex-ai',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'veo-3-1-fast-generate',
    label: 'Google Veo 3.1 Fast',
    kinds: ['t2v', 'i2v'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 25,
    maxClipSec: 8,
    resolutions: ['720p', '1080p'],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://cloud.google.com/vertex-ai',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'seedance-2-0',
    label: 'BytePlus Seedance 2.0',
    kinds: ['t2v', 'i2v'],
    status: 'active',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 12,
    maxClipSec: 10,
    resolutions: ['720p', '1080p'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://www.volcengine.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'seedance-2-0-fast',
    label: 'BytePlus Seedance 2.0 Fast',
    kinds: ['t2v', 'i2v'],
    status: 'active',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 8,
    maxClipSec: 10,
    resolutions: ['720p'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://www.volcengine.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'seedance-1-0-pro-fast',
    label: 'BytePlus Seedance 1.0 Pro Fast',
    kinds: ['t2v', 'i2v'],
    status: 'disabled',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 6,
    maxClipSec: 10,
    resolutions: ['720p'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://www.volcengine.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'kling-2-1',
    label: 'Kling 2.1',
    kinds: ['t2v', 'i2v'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 15,
    maxClipSec: 10,
    resolutions: ['720p', '1080p'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://fal.ai/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'kling-3',
    label: 'Kling 3',
    kinds: ['t2v', 'i2v'],
    status: 'preview',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 20,
    maxClipSec: 10,
    resolutions: ['720p', '1080p'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://fal.ai/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'wan-2-7',
    label: 'Wan 2.7',
    kinds: ['t2v'],
    status: 'preview',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 10,
    maxClipSec: 8,
    resolutions: ['720p'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://fal.ai/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'pika-mcp',
    label: 'Pika MCP',
    kinds: ['t2v', 'i2v', 'lipsync'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 20,
    maxClipSec: 10,
    resolutions: ['720p', '1080p'],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://mcp.pika.me/api/mcp',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'mochi-v1',
    label: 'Mochi v1',
    kinds: ['t2v'],
    status: 'disabled',
    requiresApiKey: true,
    dataEgress: 'cloud',
    defaultCostPerSecCents: 2,
    maxClipSec: 6,
    resolutions: ['480p'],
    supportsAudio: false,
    license: 'commercial-ok',
    sourceUrl: 'https://fal.ai/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'kokoro',
    label: 'Kokoro local',
    kinds: ['voice'],
    status: 'active',
    requiresApiKey: false,
    dataEgress: 'local',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://huggingface.co/hexgrad/Kokoro-82M',
    lastVerifiedAt: '2026-05-18',
    probeRequired: false,
  },
  {
    id: 'elevenlabs',
    label: 'ElevenLabs',
    kinds: ['voice'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://elevenlabs.io/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'cartesia',
    label: 'Cartesia Sonic',
    kinds: ['voice'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://cartesia.ai/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'openai-tts',
    label: 'OpenAI TTS',
    kinds: ['voice'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://platform.openai.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'gemini-tts',
    label: 'Gemini TTS',
    kinds: ['voice'],
    status: 'preview',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://ai.google.dev/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'hume-octave',
    label: 'Hume Octave',
    kinds: ['voice'],
    status: 'preview',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://hume.ai/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'indextts',
    label: 'IndexTTS',
    kinds: ['voice'],
    status: 'disabled',
    requiresApiKey: false,
    dataEgress: 'local',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-with-permission',
    sourceUrl: 'https://github.com/index-tts/index-tts',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
    notes: 'Requires INDEXTTS_LICENSE_OK=1 before packaged use.',
  },
  {
    id: 'whisperx-local',
    label: 'WhisperX local',
    kinds: ['transcribe'],
    status: 'active',
    requiresApiKey: false,
    dataEgress: 'local',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://github.com/m-bain/whisperX',
    lastVerifiedAt: '2026-05-18',
    probeRequired: false,
  },
  {
    id: 'auto-subs-local',
    label: 'Auto Subs local',
    kinds: ['transcribe'],
    status: 'preview',
    requiresApiKey: false,
    dataEgress: 'local',
    maxClipSec: 0,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://github.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: false,
  },
  {
    id: 'pexels',
    label: 'Pexels',
    kinds: ['broll'],
    status: 'active',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: ['720p', '1080p'],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://www.pexels.com/api/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'pixabay',
    label: 'Pixabay',
    kinds: ['broll'],
    status: 'active',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: ['720p', '1080p'],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://pixabay.com/api/docs/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'storyblocks',
    label: 'Storyblocks',
    kinds: ['broll'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 0,
    resolutions: ['720p', '1080p', '4K'],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://www.storyblocks.com/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'elevenlabs-music',
    label: 'ElevenLabs Music',
    kinds: ['music'],
    status: 'account-gated',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 300,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://elevenlabs.io/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'stable-audio',
    label: 'Stable Audio',
    kinds: ['music'],
    status: 'preview',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 300,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://stability.ai/',
    lastVerifiedAt: '2026-05-18',
    probeRequired: true,
  },
  {
    id: 'minimax-music',
    label: 'MiniMax Music 2.6',
    kinds: ['music'],
    status: 'preview',
    requiresApiKey: true,
    dataEgress: 'cloud',
    maxClipSec: 300,
    resolutions: [],
    supportsAudio: true,
    license: 'commercial-ok',
    sourceUrl: 'https://www.minimax.io/',
    lastVerifiedAt: '2026-06-06',
    probeRequired: true,
  },
];

export function getProviderCapability(
  id: ProviderId,
): ProviderCapability | undefined {
  return VIDEO_PROVIDER_CAPABILITIES.find((provider) => provider.id === id);
}
