import {
  findImportedVividOverlayPreset,
  vividOverlayControlDefaults,
  vividOverlayControlErrors,
  type VividOverlayControlValue,
  type VividOverlayParams,
  type VividOverlayPresetDef,
} from '@neumar/video-ir';

// Curated vivid-overlay preset catalog (frontend copy).
//
// This registry is duplicated in src-api/src/shared/video/overlays/registry.ts
// because the `@/*` path alias does not cross the workspace boundary. The two
// copies are pinned by src-api/test/unit/video/overlay-registry-parity.test.ts
// — edit both together, same discipline as VIDEO_TRANSITION_REGISTRY.
//
// Every entry with bundled assets needs a license record.
const GIF_STICKER_SENTINEL_DURATION_MS = 36_000_000;

export const VIDEO_OVERLAY_REGISTRY = [
  {
    id: 'html.marker-highlight',
    backend: 'html',
    category: 'callout',
    labelKey: 'overlays.markerHighlight',
    descriptionKey: 'overlays.markerHighlightDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Highlight this',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ffd166',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 64,
        min: 24,
        max: 160,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'marker-highlight',
    defaultDurationMs: 2500,
    minDurationMs: 500,
    tags: ['highlight', 'marker', 'sweep', 'emphasis'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
    taste: {
      intent: 'annotation',
      targets: ['text', 'section'],
      bestFor: [
        'highlighting one quoted phrase or key sentence',
        'drawing attention to a short UI or content region',
      ],
      avoidWhen: [
        'the scene already has another attention-grabbing callout',
        'the highlighted copy is long or compliance-heavy',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'none' },
      reducedMotion: 'poster',
      motionTokens: { duration: 'base', easing: 'ease-out' },
    },
  },
  {
    id: 'html.lower-third',
    backend: 'html',
    category: 'title',
    labelKey: 'overlays.lowerThird',
    descriptionKey: 'overlays.lowerThirdDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Your Name',
      },
      {
        id: 'subtitle',
        type: 'text',
        labelKey: 'overlays.controls.subtitle',
        defaultValue: 'What you do',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#33ccff',
      },
    ],
    capability: 'native',
    documentId: 'lower-third',
    defaultDurationMs: 3000,
    minDurationMs: 800,
    tags: ['name', 'intro', 'broadcast', 'banner', 'lower third'],
    aspectAffinity: 'landscape',
    anchor: 'bottom',
    previewBackground: 'photo',
    taste: {
      intent: 'entrance',
      targets: ['text'],
      bestFor: [
        'introducing a speaker, host, or segment title',
        'adding broadcast-style identity without covering the subject',
      ],
      avoidWhen: [
        'the scene has no named person or segment to identify',
        'the lower third would cover important captions or UI controls',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'none' },
      reducedMotion: 'crossfade',
      motionTokens: { duration: 'base', easing: 'ease-out' },
    },
  },
  {
    id: 'html.callout-box',
    backend: 'html',
    category: 'callout',
    labelKey: 'overlays.calloutBox',
    descriptionKey: 'overlays.calloutBoxDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Did you know?',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#7c3aed',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 34,
        min: 18,
        max: 80,
        step: 2,
      },
    ],
    capability: 'native',
    documentId: 'callout-box',
    defaultDurationMs: 3200,
    minDurationMs: 600,
    tags: ['speech', 'bubble', 'note', 'fact'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'text.title-pop',
    backend: 'text-motion',
    category: 'title',
    labelKey: 'overlays.titlePop',
    descriptionKey: 'overlays.titlePopDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'BIG TITLE',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ffffff',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 92,
        min: 32,
        max: 200,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'title-pop',
    defaultDurationMs: 2200,
    minDurationMs: 500,
    tags: ['title', 'kinetic', 'words', 'uppercase'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
    taste: {
      intent: 'text-kinetic',
      targets: ['text'],
      bestFor: [
        'short title cards with one punchy phrase',
        'opening beats that need a playful headline reveal',
      ],
      avoidWhen: [
        'the text is more than five words',
        'the tone is serious, legal, or data-dense',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'none' },
      reducedMotion: 'scale-only',
      motionTokens: { duration: 'base', easing: 'spring-snappy' },
    },
  },
  {
    id: 'sticker.gif',
    backend: 'gif',
    category: 'sticker',
    labelKey: 'overlays.gifSticker',
    descriptionKey: 'overlays.gifStickerDescription',
    controls: [],
    capability: 'native',
    requiresSourceAsset: true,
    // GIF documents loop on the file's intrinsic duration; this sentinel keeps
    // clip-level 'hold' from ever clamping local time.
    defaultDurationMs: GIF_STICKER_SENTINEL_DURATION_MS,
    minDurationMs: 100,
    tags: ['gif', 'sticker', 'loop', 'asset'],
    aspectAffinity: 'any',
    anchor: 'center',
  },
  {
    id: 'lottie.pulse',
    backend: 'lottie',
    category: 'ambient',
    labelKey: 'overlays.lottiePulse',
    descriptionKey: 'overlays.lottiePulseDescription',
    controls: [],
    capability: 'native',
    documentId: 'lottie:pulse-badge',
    defaultDurationMs: 2000,
    minDurationMs: 300,
    license: { source: 'first-party (hand-authored)', license: 'MIT' },
    tags: ['pulse', 'badge', 'accent', 'ambient'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'text.kinetic-words',
    backend: 'text-motion',
    category: 'title',
    labelKey: 'overlays.kineticWords',
    descriptionKey: 'overlays.kineticWordsDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'One word at a time',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ffffff',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 72,
        min: 28,
        max: 160,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'kinetic-words',
    defaultDurationMs: 2600,
    minDurationMs: 600,
    tags: ['kinetic', 'words', 'stagger', 'title'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'text.tracking-expand',
    backend: 'text-motion',
    category: 'title',
    labelKey: 'overlays.trackingExpand',
    descriptionKey: 'overlays.trackingExpandDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'CINEMATIC',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ffffff',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 64,
        min: 24,
        max: 140,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'tracking-expand',
    defaultDurationMs: 2400,
    minDurationMs: 700,
    tags: ['cinematic', 'letterspacing', 'elegant', 'film'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'text.glitch-title',
    backend: 'text-motion',
    category: 'title',
    labelKey: 'overlays.glitchTitle',
    descriptionKey: 'overlays.glitchTitleDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'GLITCH',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ffffff',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 84,
        min: 32,
        max: 180,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'glitch-title',
    defaultDurationMs: 2200,
    minDurationMs: 500,
    tags: ['glitch', 'rgb', 'gaming', 'tech'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'text.neon-glow',
    backend: 'text-motion',
    category: 'title',
    labelKey: 'overlays.neonGlow',
    descriptionKey: 'overlays.neonGlowDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Neon nights',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#22d3ee',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 76,
        min: 28,
        max: 160,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'neon-glow',
    defaultDurationMs: 4300,
    minDurationMs: 1200,
    tags: ['neon', 'glow', 'flicker', 'retro'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'text.typewriter',
    backend: 'text-motion',
    category: 'title',
    labelKey: 'overlays.typewriter',
    descriptionKey: 'overlays.typewriterDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Typing it out…',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ffffff',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 54,
        min: 20,
        max: 120,
        step: 2,
      },
    ],
    capability: 'native',
    documentId: 'typewriter',
    defaultDurationMs: 4600,
    minDurationMs: 1000,
    tags: ['typewriter', 'mono', 'caret', 'code'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.masked-reveal',
    backend: 'html',
    category: 'title',
    labelKey: 'overlays.maskedReveal',
    descriptionKey: 'overlays.maskedRevealDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'The Reveal',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#f59e0b',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 68,
        min: 28,
        max: 150,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'masked-reveal',
    defaultDurationMs: 2400,
    minDurationMs: 700,
    tags: ['mask', 'wipe', 'reveal', 'block'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.lower-third-glass',
    backend: 'html',
    category: 'title',
    labelKey: 'overlays.lowerThirdGlass',
    descriptionKey: 'overlays.lowerThirdGlassDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Your Name',
      },
      {
        id: 'subtitle',
        type: 'text',
        labelKey: 'overlays.controls.subtitle',
        defaultValue: 'What you do',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#34d399',
      },
    ],
    capability: 'native',
    documentId: 'lower-third-glass',
    defaultDurationMs: 3000,
    minDurationMs: 800,
    tags: ['lower third', 'glass', 'blur', 'modern'],
    aspectAffinity: 'landscape',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.lower-third-broadcast',
    backend: 'html',
    category: 'title',
    labelKey: 'overlays.lowerThirdBroadcast',
    descriptionKey: 'overlays.lowerThirdBroadcastDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Alex Rivera',
      },
      {
        id: 'subtitle',
        type: 'text',
        labelKey: 'overlays.controls.subtitle',
        defaultValue: 'Senior Correspondent',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#dc2626',
      },
    ],
    capability: 'native',
    documentId: 'lower-third-broadcast',
    defaultDurationMs: 3200,
    minDurationMs: 900,
    tags: ['lower third', 'news', 'broadcast', 'two-tier'],
    aspectAffinity: 'landscape',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.lower-third-social',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.lowerThirdSocial',
    descriptionKey: 'overlays.lowerThirdSocialDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Your Name',
      },
      {
        id: 'subtitle',
        type: 'text',
        labelKey: 'overlays.controls.subtitle',
        defaultValue: '@handle',
      },
      {
        id: 'platform',
        type: 'select',
        labelKey: 'overlays.controls.platform',
        defaultValue: 'youtube',
        options: ['youtube', 'tiktok', 'instagram', 'x'],
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#ff0033',
      },
    ],
    capability: 'native',
    documentId: 'lower-third-social',
    defaultDurationMs: 3000,
    minDurationMs: 800,
    tags: ['handle', 'social', 'creator', 'chip'],
    aspectAffinity: 'any',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.lower-third-minimal',
    backend: 'html',
    category: 'title',
    labelKey: 'overlays.lowerThirdMinimal',
    descriptionKey: 'overlays.lowerThirdMinimalDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Your Name',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#f59e0b',
      },
    ],
    capability: 'native',
    documentId: 'lower-third-minimal',
    defaultDurationMs: 2600,
    minDurationMs: 700,
    tags: ['lower third', 'minimal', 'clean', 'portrait'],
    aspectAffinity: 'any',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.circle-marker',
    backend: 'html',
    category: 'callout',
    labelKey: 'overlays.circleMarker',
    descriptionKey: 'overlays.circleMarkerDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ef4444',
      },
      {
        id: 'strokeWidth',
        type: 'number',
        labelKey: 'overlays.controls.strokeWidth',
        defaultValue: 6,
        min: 2,
        max: 16,
        step: 1,
      },
    ],
    capability: 'native',
    documentId: 'circle-marker',
    defaultDurationMs: 2400,
    minDurationMs: 600,
    tags: ['circle', 'hand-drawn', 'annotate', 'draw'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'photo',
  },
  {
    id: 'html.arrow-label',
    backend: 'html',
    category: 'callout',
    labelKey: 'overlays.arrowLabel',
    descriptionKey: 'overlays.arrowLabelDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Look here',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#facc15',
      },
      {
        id: 'direction',
        type: 'select',
        labelKey: 'overlays.controls.direction',
        defaultValue: 'left',
        options: ['left', 'right', 'up', 'down'],
      },
    ],
    capability: 'native',
    documentId: 'arrow-label',
    defaultDurationMs: 2600,
    minDurationMs: 700,
    tags: ['arrow', 'point', 'label', 'annotate'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'photo',
  },
  {
    id: 'html.spotlight-dim',
    backend: 'html',
    category: 'callout',
    labelKey: 'overlays.spotlightDim',
    descriptionKey: 'overlays.spotlightDimDescription',
    controls: [
      {
        id: 'dimOpacity',
        type: 'number',
        labelKey: 'overlays.controls.dimOpacity',
        defaultValue: 0.55,
        min: 0.1,
        max: 0.9,
        step: 0.05,
      },
    ],
    capability: 'native',
    documentId: 'spotlight-dim',
    defaultDurationMs: 2000,
    minDurationMs: 500,
    tags: ['spotlight', 'dim', 'focus', 'vignette'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.step-pin',
    backend: 'html',
    category: 'callout',
    labelKey: 'overlays.stepPin',
    descriptionKey: 'overlays.stepPinDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: '1',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#2563eb',
      },
    ],
    capability: 'native',
    documentId: 'step-pin',
    defaultDurationMs: 2600,
    minDurationMs: 600,
    tags: ['step', 'number', 'pin', 'tutorial'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'photo',
  },
  {
    id: 'html.underline-sweep',
    backend: 'html',
    category: 'callout',
    labelKey: 'overlays.underlineSweep',
    descriptionKey: 'overlays.underlineSweepDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'underline this',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#fb923c',
      },
      {
        id: 'fontSize',
        type: 'number',
        labelKey: 'overlays.controls.fontSize',
        defaultValue: 60,
        min: 24,
        max: 140,
        step: 4,
      },
    ],
    capability: 'native',
    documentId: 'underline-sweep',
    defaultDurationMs: 2200,
    minDurationMs: 600,
    tags: ['underline', 'marker', 'sweep', 'emphasis'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.live-pill',
    backend: 'html',
    category: 'badge',
    labelKey: 'overlays.livePill',
    descriptionKey: 'overlays.livePillDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'LIVE',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#dc2626',
      },
    ],
    capability: 'native',
    documentId: 'live-pill',
    defaultDurationMs: 3800,
    minDurationMs: 800,
    tags: ['live', 'pill', 'stream', 'blink'],
    aspectAffinity: 'any',
    anchor: 'corner-tl',
    previewBackground: 'photo',
  },
  {
    id: 'html.ribbon-corner',
    backend: 'html',
    category: 'badge',
    labelKey: 'overlays.ribbonCorner',
    descriptionKey: 'overlays.ribbonCornerDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'NEW',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#16a34a',
      },
      {
        id: 'corner',
        type: 'select',
        labelKey: 'overlays.controls.corner',
        defaultValue: 'top-left',
        options: ['top-left', 'top-right'],
      },
    ],
    capability: 'native',
    documentId: 'ribbon-corner',
    defaultDurationMs: 2400,
    minDurationMs: 600,
    tags: ['ribbon', 'banner', 'sale', 'corner'],
    aspectAffinity: 'any',
    anchor: 'corner-tl',
    previewBackground: 'photo',
  },
  {
    id: 'html.rating-stars',
    backend: 'html',
    category: 'badge',
    labelKey: 'overlays.ratingStars',
    descriptionKey: 'overlays.ratingStarsDescription',
    controls: [
      {
        id: 'count',
        type: 'number',
        labelKey: 'overlays.controls.count',
        defaultValue: 5,
        min: 0,
        max: 5,
        step: 1,
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#facc15',
      },
    ],
    capability: 'native',
    documentId: 'rating-stars',
    defaultDurationMs: 2400,
    minDurationMs: 700,
    tags: ['stars', 'rating', 'review', 'score'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.verified-pop',
    backend: 'html',
    category: 'badge',
    labelKey: 'overlays.verifiedPop',
    descriptionKey: 'overlays.verifiedPopDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#3b82f6',
      },
    ],
    capability: 'native',
    documentId: 'verified-pop',
    defaultDurationMs: 2200,
    minDurationMs: 500,
    tags: ['verified', 'check', 'badge', 'seal'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'lottie.confetti',
    backend: 'lottie',
    category: 'reaction',
    labelKey: 'overlays.confetti',
    descriptionKey: 'overlays.confettiDescription',
    controls: [],
    capability: 'native',
    documentId: 'lottie:confetti',
    defaultDurationMs: 1800,
    minDurationMs: 400,
    tags: ['confetti', 'celebrate', 'party', 'burst'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
    license: { source: 'first-party (hand-authored)', license: 'MIT' },
  },
  {
    id: 'lottie.motion-favorite',
    backend: 'lottie',
    category: 'reaction',
    labelKey: 'overlays.motionFavorite',
    descriptionKey: 'overlays.motionFavoriteDescription',
    controls: [],
    capability: 'native',
    documentId: 'lottie:motion-anything/lottie-favorite',
    defaultDurationMs: 1700,
    minDurationMs: 300,
    tags: ['lottie', 'favorite', 'heart', 'reaction'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
    license: {
      source: 'motion-anything / spemer/lottie-animations-json',
      license: 'MIT (attribution required)',
    },
    taste: {
      intent: 'feedback',
      targets: ['button'],
      bestFor: [
        'favorite, like, save, or reaction moments',
        'small positive feedback beats that need a portable icon animation',
      ],
      avoidWhen: [
        'a pure text callout would communicate the message more clearly',
        'the scene already has another celebratory reaction effect',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'manual' },
      reducedMotion: 'poster',
      motionTokens: { duration: 'deliberate', easing: 'ease-out' },
    },
  },
  {
    id: 'lottie.motion-fab',
    backend: 'lottie',
    category: 'widget',
    labelKey: 'overlays.motionFab',
    descriptionKey: 'overlays.motionFabDescription',
    controls: [],
    capability: 'native',
    documentId: 'lottie:motion-anything/lottie-fab',
    defaultDurationMs: 5000,
    minDurationMs: 600,
    tags: ['lottie', 'fab', 'button', 'menu'],
    aspectAffinity: 'portrait',
    anchor: 'center',
    previewBackground: 'dark',
    license: {
      source: 'motion-anything / spemer/lottie-animations-json',
      license: 'MIT (attribution required)',
    },
    taste: {
      intent: 'feedback',
      targets: ['button'],
      bestFor: [
        'app walkthroughs that need to show a floating action button opening',
        'mobile UI explainers where the control itself is the subject',
      ],
      avoidWhen: [
        'the scene is not about app controls or workflow steps',
        'the tall source aspect would fight a horizontal composition',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'manual' },
      reducedMotion: 'poster',
      motionTokens: { duration: 'deliberate', easing: 'ease-out' },
    },
  },
  {
    id: 'lottie.motion-pagination',
    backend: 'lottie',
    category: 'progress',
    labelKey: 'overlays.motionPagination',
    descriptionKey: 'overlays.motionPaginationDescription',
    controls: [],
    capability: 'native',
    documentId: 'lottie:motion-anything/lottie-pagination',
    defaultDurationMs: 5000,
    minDurationMs: 600,
    tags: ['lottie', 'pagination', 'dots', 'progress'],
    aspectAffinity: 'landscape',
    anchor: 'bottom',
    previewBackground: 'dark',
    license: {
      source: 'motion-anything / spemer/lottie-animations-json',
      license: 'MIT (attribution required)',
    },
    taste: {
      intent: 'progress',
      targets: ['section'],
      bestFor: [
        'showing a paged carousel or multi-step UI changing state',
        'progress moments that should feel like an app indicator',
      ],
      avoidWhen: [
        'the content is not paged or step-based',
        'a textual progress label would be clearer',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'manual' },
      reducedMotion: 'poster',
      motionTokens: { duration: 'deliberate', easing: 'ease-out' },
    },
  },
  {
    id: 'lottie.motion-tab',
    backend: 'lottie',
    category: 'widget',
    labelKey: 'overlays.motionTab',
    descriptionKey: 'overlays.motionTabDescription',
    controls: [],
    capability: 'native',
    documentId: 'lottie:motion-anything/lottie-tab',
    defaultDurationMs: 3000,
    minDurationMs: 400,
    tags: ['lottie', 'tab', 'navigation', 'indicator'],
    aspectAffinity: 'landscape',
    anchor: 'bottom',
    previewBackground: 'dark',
    license: {
      source: 'motion-anything / spemer/lottie-animations-json',
      license: 'MIT (attribution required)',
    },
    taste: {
      intent: 'feedback',
      targets: ['button'],
      bestFor: [
        'mobile app navigation explainers',
        'showing a tab indicator changing selection',
      ],
      avoidWhen: [
        'there is no app-navigation context',
        'the bottom of the scene is already occupied by captions or controls',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'manual' },
      reducedMotion: 'poster',
      motionTokens: { duration: 'base', easing: 'ease-out' },
    },
  },
  {
    id: 'html.subscribe-button',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.subscribeButton',
    descriptionKey: 'overlays.subscribeButtonDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'SUBSCRIBE',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#ff0033',
      },
    ],
    capability: 'native',
    documentId: 'subscribe-button',
    defaultDurationMs: 3000,
    minDurationMs: 800,
    tags: ['subscribe', 'button', 'youtube', 'cta'],
    aspectAffinity: 'any',
    anchor: 'bottom',
    previewBackground: 'photo',
    taste: {
      intent: 'feedback',
      targets: ['button', 'text'],
      bestFor: [
        'creator calls to action near the end of a social clip',
        'explicit subscribe or follow prompts',
      ],
      avoidWhen: [
        'the video is editorial, enterprise, or documentary in tone',
        'another CTA is already visible in the same scene',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'none' },
      reducedMotion: 'scale-only',
      motionTokens: { duration: 'base', easing: 'spring-soft' },
    },
  },
  {
    id: 'html.follow-reminder',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.followReminder',
    descriptionKey: 'overlays.followReminderDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: '@yourhandle',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#ec4899',
      },
    ],
    capability: 'native',
    documentId: 'follow-reminder',
    defaultDurationMs: 3000,
    minDurationMs: 800,
    tags: ['follow', 'handle', 'heart', 'social'],
    aspectAffinity: 'any',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.link-in-bio',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.linkInBio',
    descriptionKey: 'overlays.linkInBioDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Link in bio',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#8b5cf6',
      },
    ],
    capability: 'native',
    documentId: 'link-in-bio',
    defaultDurationMs: 3200,
    minDurationMs: 800,
    tags: ['link', 'bio', 'arrow', 'cta'],
    aspectAffinity: 'portrait',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.corner-bug',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.cornerBug',
    descriptionKey: 'overlays.cornerBugDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: '@channel',
      },
      {
        id: 'corner',
        type: 'select',
        labelKey: 'overlays.controls.corner',
        defaultValue: 'bottom-right',
        options: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
      },
    ],
    capability: 'native',
    documentId: 'corner-bug',
    defaultDurationMs: 4000,
    minDurationMs: 800,
    tags: ['watermark', 'bug', 'corner', 'brand'],
    aspectAffinity: 'any',
    anchor: 'corner-br',
    previewBackground: 'photo',
  },
  {
    id: 'html.notification-toast',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.notificationToast',
    descriptionKey: 'overlays.notificationToastDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'New message',
      },
      {
        id: 'subtitle',
        type: 'text',
        labelKey: 'overlays.controls.subtitle',
        defaultValue: 'You have a new follower',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#3b82f6',
      },
    ],
    capability: 'native',
    documentId: 'notification-toast',
    defaultDurationMs: 3200,
    minDurationMs: 800,
    tags: ['notification', 'toast', 'alert', 'message'],
    aspectAffinity: 'any',
    anchor: 'top',
    previewBackground: 'photo',
  },
  {
    id: 'html.cta-banner',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.ctaBanner',
    descriptionKey: 'overlays.ctaBannerDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Try it free today',
      },
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Get started',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#16a34a',
      },
    ],
    capability: 'native',
    documentId: 'cta-banner',
    defaultDurationMs: 4200,
    minDurationMs: 1000,
    tags: ['cta', 'banner', 'button', 'bar'],
    aspectAffinity: 'any',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.floating-hearts',
    backend: 'html',
    category: 'reaction',
    labelKey: 'overlays.floatingHearts',
    descriptionKey: 'overlays.floatingHeartsDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#f43f5e',
      },
    ],
    capability: 'native',
    documentId: 'floating-hearts',
    defaultDurationMs: 4000,
    minDurationMs: 1000,
    tags: ['hearts', 'love', 'float', 'reaction'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'dark',
    taste: {
      intent: 'feedback',
      targets: ['background'],
      bestFor: [
        'celebratory social reactions',
        'softening a playful thank-you or fan response moment',
      ],
      avoidWhen: [
        'the scene is professional, urgent, or emotionally serious',
        'the subject or text needs to remain visually quiet',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'manual' },
      reducedMotion: 'none',
      motionTokens: { duration: 'slow', easing: 'ease-out' },
    },
  },
  {
    id: 'html.emoji-rain',
    backend: 'html',
    category: 'reaction',
    labelKey: 'overlays.emojiRain',
    descriptionKey: 'overlays.emojiRainDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: '🎉',
      },
    ],
    capability: 'native',
    documentId: 'emoji-rain',
    defaultDurationMs: 4000,
    minDurationMs: 1000,
    tags: ['emoji', 'rain', 'fall', 'party'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'dark',
  },
  {
    id: 'html.fire-streak',
    backend: 'html',
    category: 'reaction',
    labelKey: 'overlays.fireStreak',
    descriptionKey: 'overlays.fireStreakDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: '7',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#f97316',
      },
    ],
    capability: 'native',
    documentId: 'fire-streak',
    defaultDurationMs: 2400,
    minDurationMs: 600,
    tags: ['fire', 'streak', 'count', 'hot'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.clap-burst',
    backend: 'html',
    category: 'reaction',
    labelKey: 'overlays.clapBurst',
    descriptionKey: 'overlays.clapBurstDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#facc15',
      },
    ],
    capability: 'native',
    documentId: 'clap-burst',
    defaultDurationMs: 2200,
    minDurationMs: 500,
    tags: ['clap', 'applause', 'burst', 'praise'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.chat-bubbles',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.chatBubbles',
    descriptionKey: 'overlays.chatBubblesDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Hey! Did you see this?|Yes 😍',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#3b82f6',
      },
    ],
    capability: 'native',
    documentId: 'chat-bubbles',
    defaultDurationMs: 3600,
    minDurationMs: 900,
    tags: ['chat', 'messages', 'bubbles', 'conversation'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.comment-card',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.commentCard',
    descriptionKey: 'overlays.commentCardDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: '@username',
      },
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'This is amazing!',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#6366f1',
      },
    ],
    capability: 'native',
    documentId: 'comment-card',
    defaultDurationMs: 3000,
    minDurationMs: 800,
    tags: ['comment', 'card', 'avatar', 'social'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.quote-card',
    backend: 'html',
    category: 'social',
    labelKey: 'overlays.quoteCard',
    descriptionKey: 'overlays.quoteCardDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'The best way to predict the future is to invent it.',
      },
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Alan Kay',
      },
    ],
    capability: 'native',
    documentId: 'quote-card',
    defaultDurationMs: 3600,
    minDurationMs: 900,
    tags: ['quote', 'card', 'attribution', 'saying'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.progress-top',
    backend: 'html',
    category: 'progress',
    labelKey: 'overlays.progressTop',
    descriptionKey: 'overlays.progressTopDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ef4444',
      },
    ],
    capability: 'native',
    documentId: 'progress-top',
    defaultDurationMs: 10000,
    minDurationMs: 1000,
    tags: ['progress', 'bar', 'timer', 'top'],
    previewPosterMs: 6000,
    aspectAffinity: 'any',
    anchor: 'top',
    previewBackground: 'photo',
    taste: {
      intent: 'progress',
      targets: ['screen'],
      bestFor: [
        'showing elapsed time in tutorials, demos, or chaptered clips',
        'giving viewers a passive sense of clip progress',
      ],
      avoidWhen: [
        'the scene is not time-bound',
        'another progress or countdown element is already present',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'manual' },
      reducedMotion: 'poster',
      motionTokens: { duration: 'deliberate', easing: 'linear' },
    },
  },
  {
    id: 'html.progress-chapters',
    backend: 'html',
    category: 'progress',
    labelKey: 'overlays.progressChapters',
    descriptionKey: 'overlays.progressChaptersDescription',
    controls: [
      {
        id: 'count',
        type: 'number',
        labelKey: 'overlays.controls.count',
        defaultValue: 2,
        min: 1,
        max: 5,
        step: 1,
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#22d3ee',
      },
    ],
    capability: 'native',
    documentId: 'progress-chapters',
    defaultDurationMs: 2800,
    minDurationMs: 700,
    tags: ['chapters', 'segments', 'progress', 'steps'],
    aspectAffinity: 'any',
    anchor: 'bottom',
    previewBackground: 'photo',
  },
  {
    id: 'html.countdown-ring',
    backend: 'html',
    category: 'progress',
    labelKey: 'overlays.countdownRing',
    descriptionKey: 'overlays.countdownRingDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#8b5cf6',
      },
    ],
    capability: 'native',
    documentId: 'countdown-ring',
    defaultDurationMs: 5000,
    minDurationMs: 1000,
    tags: ['countdown', 'ring', 'timer', 'numbers'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.part-indicator',
    backend: 'html',
    category: 'progress',
    labelKey: 'overlays.partIndicator',
    descriptionKey: 'overlays.partIndicatorDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'PART 2/5',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#0ea5e9',
      },
    ],
    capability: 'native',
    documentId: 'part-indicator',
    defaultDurationMs: 2600,
    minDurationMs: 600,
    tags: ['part', 'series', 'chip', 'indicator'],
    aspectAffinity: 'any',
    anchor: 'corner-tl',
    previewBackground: 'photo',
  },
  {
    id: 'html.counter-ticker',
    backend: 'html',
    category: 'widget',
    labelKey: 'overlays.counterTicker',
    descriptionKey: 'overlays.counterTickerDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: '100',
      },
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'subscribers',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#34d399',
      },
    ],
    capability: 'native',
    documentId: 'counter-ticker',
    defaultDurationMs: 3200,
    minDurationMs: 800,
    tags: ['counter', 'ticker', 'digits', 'stats'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.vs-card',
    backend: 'html',
    category: 'widget',
    labelKey: 'overlays.vsCard',
    descriptionKey: 'overlays.vsCardDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Option A',
      },
      {
        id: 'subtitle',
        type: 'text',
        labelKey: 'overlays.controls.subtitle',
        defaultValue: 'Option B',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#f59e0b',
      },
    ],
    capability: 'native',
    documentId: 'vs-card',
    defaultDurationMs: 2800,
    minDurationMs: 700,
    tags: ['versus', 'compare', 'battle', 'split'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.percentage-ring',
    backend: 'html',
    category: 'widget',
    labelKey: 'overlays.percentageRing',
    descriptionKey: 'overlays.percentageRingDescription',
    controls: [
      {
        id: 'count',
        type: 'number',
        labelKey: 'overlays.controls.count',
        defaultValue: 87,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'faster',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#22d3ee',
      },
    ],
    capability: 'native',
    documentId: 'percentage-ring',
    defaultDurationMs: 3200,
    minDurationMs: 800,
    tags: ['percentage', 'ring', 'stat', 'gauge'],
    aspectAffinity: 'any',
    anchor: 'center',
    previewBackground: 'dark',
  },
  {
    id: 'html.vignette',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.vignette',
    descriptionKey: 'overlays.vignetteDescription',
    controls: [
      {
        id: 'dimOpacity',
        type: 'number',
        labelKey: 'overlays.controls.dimOpacity',
        defaultValue: 0.45,
        min: 0.1,
        max: 0.9,
        step: 0.05,
      },
    ],
    capability: 'native',
    documentId: 'vignette',
    defaultDurationMs: 4000,
    minDurationMs: 800,
    tags: ['vignette', 'dim', 'cinematic', 'mood'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
    taste: {
      intent: 'ambient',
      targets: ['screen', 'background'],
      bestFor: [
        'subtly focusing attention toward the center of footage',
        'adding a cinematic finish behind titles or captions',
      ],
      avoidWhen: [
        'the footage is already dark or contrast-heavy',
        'screen recordings need edge-to-edge readability',
      ],
      restraint: {
        maxPerScene: 1,
        maxSimultaneous: 1,
        loopPolicy: 'single-ambient',
      },
      reducedMotion: 'poster',
      motionTokens: { duration: 'slow', easing: 'ease-in-out' },
    },
  },
  {
    id: 'html.film-grain',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.filmGrain',
    descriptionKey: 'overlays.filmGrainDescription',
    controls: [
      {
        id: 'dimOpacity',
        type: 'number',
        labelKey: 'overlays.controls.dimOpacity',
        defaultValue: 0.18,
        min: 0.05,
        max: 0.6,
        step: 0.01,
      },
    ],
    capability: 'native',
    documentId: 'film-grain',
    defaultDurationMs: 1000,
    minDurationMs: 400,
    tags: ['grain', 'film', 'noise', 'texture'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.vhs-scanlines',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.vhsScanlines',
    descriptionKey: 'overlays.vhsScanlinesDescription',
    controls: [
      {
        id: 'dimOpacity',
        type: 'number',
        labelKey: 'overlays.controls.dimOpacity',
        defaultValue: 0.35,
        min: 0.1,
        max: 0.8,
        step: 0.05,
      },
    ],
    capability: 'native',
    documentId: 'vhs-scanlines',
    defaultDurationMs: 3000,
    minDurationMs: 600,
    tags: ['vhs', 'retro', 'scanlines', 'analog'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.light-leak',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.lightLeak',
    descriptionKey: 'overlays.lightLeakDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#fbbf24',
      },
    ],
    capability: 'native',
    documentId: 'light-leak',
    defaultDurationMs: 3500,
    minDurationMs: 800,
    tags: ['light', 'leak', 'warm', 'flare'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.bokeh-particles',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.bokehParticles',
    descriptionKey: 'overlays.bokehParticlesDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#93c5fd',
      },
    ],
    capability: 'native',
    documentId: 'bokeh-particles',
    defaultDurationMs: 6000,
    minDurationMs: 1000,
    tags: ['bokeh', 'particles', 'dreamy', 'ambient'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.snow',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.snow',
    descriptionKey: 'overlays.snowDescription',
    controls: [],
    capability: 'native',
    documentId: 'snow',
    defaultDurationMs: 5000,
    minDurationMs: 1000,
    tags: ['snow', 'winter', 'falling', 'ambient'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.rain',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.rain',
    descriptionKey: 'overlays.rainDescription',
    controls: [
      {
        id: 'dimOpacity',
        type: 'number',
        labelKey: 'overlays.controls.dimOpacity',
        defaultValue: 0.4,
        min: 0.1,
        max: 0.8,
        step: 0.05,
      },
    ],
    capability: 'native',
    documentId: 'rain',
    defaultDurationMs: 1600,
    minDurationMs: 400,
    tags: ['rain', 'storm', 'weather', 'ambient'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.letterbox',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.letterbox',
    descriptionKey: 'overlays.letterboxDescription',
    controls: [
      {
        id: 'count',
        type: 'number',
        labelKey: 'overlays.controls.count',
        defaultValue: 12,
        min: 5,
        max: 20,
        step: 1,
      },
    ],
    capability: 'native',
    documentId: 'letterbox',
    defaultDurationMs: 1200,
    minDurationMs: 400,
    tags: ['letterbox', 'cinematic', 'bars', 'widescreen'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.rgb-split-pulse',
    backend: 'html',
    category: 'screen',
    labelKey: 'overlays.rgbSplitPulse',
    descriptionKey: 'overlays.rgbSplitPulseDescription',
    controls: [
      {
        id: 'dimOpacity',
        type: 'number',
        labelKey: 'overlays.controls.dimOpacity',
        defaultValue: 0.3,
        min: 0.1,
        max: 0.7,
        step: 0.05,
      },
    ],
    capability: 'native',
    documentId: 'rgb-split-pulse',
    defaultDurationMs: 900,
    minDurationMs: 400,
    tags: ['rgb', 'glitch', 'pulse', 'edges'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.rounded-frame',
    backend: 'html',
    category: 'frame',
    labelKey: 'overlays.roundedFrame',
    descriptionKey: 'overlays.roundedFrameDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ffffff',
      },
      {
        id: 'strokeWidth',
        type: 'number',
        labelKey: 'overlays.controls.strokeWidth',
        defaultValue: 5,
        min: 2,
        max: 14,
        step: 1,
      },
      {
        id: 'count',
        type: 'number',
        labelKey: 'overlays.controls.count',
        defaultValue: 24,
        min: 0,
        max: 48,
        step: 2,
      },
    ],
    capability: 'native',
    documentId: 'rounded-frame',
    defaultDurationMs: 1600,
    minDurationMs: 500,
    tags: ['frame', 'border', 'rounded', 'outline'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
    taste: {
      intent: 'frame',
      targets: ['frame', 'screen'],
      bestFor: [
        'contained previews, screenshots, or product demo footage',
        'giving a clip a polished framed edge without changing the media',
      ],
      avoidWhen: [
        'the footage already has a device mockup or border',
        'the subject needs to bleed fully to the edge',
      ],
      restraint: { maxPerScene: 1, maxSimultaneous: 1, loopPolicy: 'none' },
      reducedMotion: 'poster',
      motionTokens: { duration: 'fast', easing: 'ease-out' },
    },
  },
  {
    id: 'html.polaroid',
    backend: 'html',
    category: 'frame',
    labelKey: 'overlays.polaroid',
    descriptionKey: 'overlays.polaroidDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Summer 2026',
      },
    ],
    capability: 'native',
    documentId: 'polaroid',
    defaultDurationMs: 2200,
    minDurationMs: 600,
    tags: ['polaroid', 'photo', 'retro', 'caption'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.phone-mockup',
    backend: 'html',
    category: 'frame',
    labelKey: 'overlays.phoneMockup',
    descriptionKey: 'overlays.phoneMockupDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#111827',
      },
    ],
    capability: 'native',
    documentId: 'phone-mockup',
    defaultDurationMs: 1800,
    minDurationMs: 500,
    tags: ['phone', 'mockup', 'bezel', 'device'],
    aspectAffinity: 'landscape',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.tape-corners',
    backend: 'html',
    category: 'frame',
    labelKey: 'overlays.tapeCorners',
    descriptionKey: 'overlays.tapeCornersDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#e5e7eb',
      },
    ],
    capability: 'native',
    documentId: 'tape-corners',
    defaultDurationMs: 1400,
    minDurationMs: 500,
    tags: ['tape', 'scrapbook', 'corners', 'craft'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.neon-border',
    backend: 'html',
    category: 'frame',
    labelKey: 'overlays.neonBorder',
    descriptionKey: 'overlays.neonBorderDescription',
    controls: [
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#22d3ee',
      },
    ],
    capability: 'native',
    documentId: 'neon-border',
    defaultDurationMs: 2400,
    minDurationMs: 600,
    tags: ['neon', 'border', 'glow', 'pulse'],
    aspectAffinity: 'any',
    anchor: 'full',
    previewBackground: 'photo',
  },
  {
    id: 'html.location-pin',
    backend: 'html',
    category: 'widget',
    labelKey: 'overlays.locationPin',
    descriptionKey: 'overlays.locationPinDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'Lisbon, Portugal',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#ef4444',
      },
    ],
    capability: 'native',
    documentId: 'location-pin',
    defaultDurationMs: 2600,
    minDurationMs: 700,
    tags: ['location', 'pin', 'travel', 'map'],
    aspectAffinity: 'any',
    anchor: 'corner-tl',
    previewBackground: 'photo',
  },
  {
    id: 'html.timestamp-chip',
    backend: 'html',
    category: 'widget',
    labelKey: 'overlays.timestampChip',
    descriptionKey: 'overlays.timestampChipDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: 'JUL 07 2026 · 14:32',
      },
    ],
    capability: 'native',
    documentId: 'timestamp-chip',
    defaultDurationMs: 2200,
    minDurationMs: 600,
    tags: ['timestamp', 'date', 'chip', 'mono'],
    aspectAffinity: 'any',
    anchor: 'corner-tr',
    previewBackground: 'photo',
  },
  {
    id: 'html.now-playing',
    backend: 'html',
    category: 'widget',
    labelKey: 'overlays.nowPlaying',
    descriptionKey: 'overlays.nowPlayingDescription',
    controls: [
      {
        id: 'title',
        type: 'text',
        labelKey: 'overlays.controls.title',
        defaultValue: 'Song title',
      },
      {
        id: 'subtitle',
        type: 'text',
        labelKey: 'overlays.controls.subtitle',
        defaultValue: 'Artist',
      },
      {
        id: 'accentColor',
        type: 'color',
        labelKey: 'overlays.controls.accentColor',
        defaultValue: '#22c55e',
      },
    ],
    capability: 'native',
    documentId: 'now-playing',
    defaultDurationMs: 3600,
    minDurationMs: 900,
    tags: ['music', 'player', 'eq', 'card'],
    aspectAffinity: 'any',
    anchor: 'corner-bl',
    previewBackground: 'dark',
  },
  {
    id: 'html.hashtag-chip',
    backend: 'html',
    category: 'widget',
    labelKey: 'overlays.hashtagChip',
    descriptionKey: 'overlays.hashtagChipDescription',
    controls: [
      {
        id: 'text',
        type: 'text',
        labelKey: 'overlays.controls.text',
        defaultValue: '#trending',
      },
      {
        id: 'color',
        type: 'color',
        labelKey: 'overlays.controls.color',
        defaultValue: '#0ea5e9',
      },
    ],
    capability: 'native',
    documentId: 'hashtag-chip',
    defaultDurationMs: 2000,
    minDurationMs: 500,
    tags: ['hashtag', 'chip', 'social', 'pop'],
    aspectAffinity: 'any',
    anchor: 'bottom',
    previewBackground: 'dark',
  },
] as const satisfies readonly VividOverlayPresetDef[];

export type VideoOverlayPresetId =
  (typeof VIDEO_OVERLAY_REGISTRY)[number]['id'];

export function findVividOverlayPreset(
  presetId: string,
): VividOverlayPresetDef | undefined {
  return VIDEO_OVERLAY_REGISTRY.find((preset) => preset.id === presetId);
}

export interface ResolvedVividOverlay {
  preset: VividOverlayPresetDef;
  /** Preset defaults overlaid with the clip's stored control values. */
  controls: Record<string, VividOverlayControlValue>;
  errors: string[];
}

/**
 * Resolve a clip's params payload against the catalog: unknown preset returns
 * null; known preset returns merged controls plus any validation problems.
 */
export function resolveVividOverlay(
  params: VividOverlayParams,
): ResolvedVividOverlay | null {
  const preset =
    findVividOverlayPreset(params.presetId) ??
    findImportedVividOverlayPreset(params.presetId);
  if (!preset || preset.backend !== params.backend) return null;
  return {
    preset,
    controls: {
      ...vividOverlayControlDefaults(preset.controls),
      ...params.controls,
    },
    errors: vividOverlayControlErrors(params.controls, preset.controls),
  };
}
