import { useCurrentFrame, useVideoConfig } from 'remotion';

interface WordTimestamp {
  word: string;
  start: number; // seconds
  end: number;
}

/**
 * Syncs visual elements to word-level voiceover timestamps.
 * Timestamps are generated by Deepgram/Whisper from voiceover MP3s.
 */
export function useVoiceoverSync(timestamps: WordTimestamp[]) {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const currentTime = frame / fps;

  const currentWordIndex = timestamps.findIndex(
    (w) => currentTime >= w.start && currentTime <= w.end,
  );

  const spokenSoFar = timestamps
    .filter((w) => currentTime >= w.start)
    .map((w) => w.word)
    .join(' ');

  const currentWord =
    currentWordIndex >= 0 ? timestamps[currentWordIndex].word : null;

  return { currentWordIndex, currentWord, spokenSoFar, currentTime };
}
