/**
 * AutomationTriggerConfig
 *
 * Trigger configuration form section with dynamic fields based on trigger type.
 */

import { formatAutomationTriggerSummary } from '@/shared/lib/schedule-summary';
import { useLanguage } from '@/shared/providers/language-provider';
import type {
  AutomationTrigger,
  AutomationTriggerType,
  ScheduleKind,
} from '@/shared/types/automation';

import { CronExpressionInput } from './CronExpressionInput';
import { QueuePickupSettings } from './QueuePickupSettings';
import { WebhookInfo } from './WebhookInfo';

interface AutomationTriggerConfigProps {
  trigger: AutomationTrigger;
  onChange: (trigger: AutomationTrigger) => void;
  /** Whether the automation is already created (webhook info is read-only) */
  isEdit?: boolean;
}

const TRIGGER_TYPES: AutomationTriggerType[] = [
  'cron',
  'webhook',
  'heartbeat',
  'manual',
];

export function AutomationTriggerConfig({
  trigger,
  onChange,
  isEdit,
}: AutomationTriggerConfigProps) {
  const { t } = useLanguage();
  const scheduleSummary = formatAutomationTriggerSummary(
    trigger,
    t.automation.scheduleSummary,
  );

  const handleTypeChange = (type: AutomationTriggerType) => {
    switch (type) {
      case 'cron':
        onChange({ type: 'cron', schedule: { kind: 'cron', cronExpr: '' } });
        break;
      case 'webhook':
        // Webhook slug/token are auto-generated by the backend
        onChange({
          type: 'webhook',
          webhook: { slug: '', token: '' },
        });
        break;
      case 'heartbeat':
        onChange({
          type: 'heartbeat',
          heartbeat: { intervalMs: 30 * 60_000 },
        });
        break;
      case 'manual':
        onChange({ type: 'manual' });
        break;
    }
  };

  return (
    <div className="space-y-4">
      {/* Trigger Type Selector */}
      <div>
        <label className="text-foreground mb-1.5 block text-sm font-medium">
          {t.automation.fields.triggerType}
        </label>
        <div className="flex flex-wrap gap-2">
          {TRIGGER_TYPES.map((type) => (
            <button
              key={type}
              type="button"
              onClick={() => handleTypeChange(type)}
              className={`rounded-md border px-3 py-1.5 text-sm transition-colors ${
                trigger.type === type
                  ? 'border-primary bg-primary/10 text-primary font-medium'
                  : 'border-border text-muted-foreground hover:bg-muted'
              }`}
              aria-label={`Select trigger type: ${t.automation.trigger[type]}`}
            >
              {t.automation.trigger[type]}
            </button>
          ))}
        </div>
      </div>

      {scheduleSummary && (
        <div className="bg-muted text-muted-foreground inline-flex rounded-full px-2.5 py-1 text-xs">
          {scheduleSummary}
        </div>
      )}

      {/* Cron Configuration */}
      {trigger.type === 'cron' && (
        <div className="space-y-3">
          {/* Schedule Kind */}
          <div>
            <label className="text-muted-foreground mb-1 block text-xs font-medium">
              {t.automation.fields.schedule}
            </label>
            <select
              value={trigger.schedule.kind}
              onChange={(e) =>
                onChange({
                  ...trigger,
                  schedule: {
                    ...trigger.schedule,
                    kind: e.target.value as ScheduleKind,
                  },
                })
              }
              className="bg-background text-foreground border-input w-full rounded-md border px-3 py-2 text-sm"
              aria-label={t.automation.fields.schedule}
            >
              <option value="cron">{t.automation.schedule.cron}</option>
              <option value="interval">{t.automation.schedule.interval}</option>
              <option value="once">{t.automation.schedule.once}</option>
            </select>
          </div>

          {/* Cron Expression */}
          {trigger.schedule.kind === 'cron' && (
            <CronExpressionInput
              value={trigger.schedule.cronExpr ?? ''}
              onChange={(cronExpr) =>
                onChange({
                  ...trigger,
                  schedule: { ...trigger.schedule, cronExpr },
                })
              }
            />
          )}

          {/* Interval */}
          {trigger.schedule.kind === 'interval' && (
            <div>
              <label className="text-muted-foreground mb-1 block text-xs font-medium">
                {t.automation.fields.intervalMinutes}
              </label>
              <input
                type="number"
                min={1}
                value={Math.round(
                  (trigger.schedule.intervalMs ?? 60000) / 60000,
                )}
                onChange={(e) =>
                  onChange({
                    ...trigger,
                    schedule: {
                      ...trigger.schedule,
                      intervalMs: parseInt(e.target.value, 10) * 60000,
                    },
                  })
                }
                className="bg-background text-foreground border-input w-full rounded-md border px-3 py-2 text-sm"
                aria-label={t.automation.fields.interval}
              />
            </div>
          )}

          {/* One-time datetime */}
          {trigger.schedule.kind === 'once' && (
            <div>
              <label className="text-muted-foreground mb-1 block text-xs font-medium">
                {t.automation.fields.dateTime}
              </label>
              <input
                type="datetime-local"
                value={trigger.schedule.at ?? ''}
                onChange={(e) =>
                  onChange({
                    ...trigger,
                    schedule: { ...trigger.schedule, at: e.target.value },
                  })
                }
                className="bg-background text-foreground border-input w-full rounded-md border px-3 py-2 text-sm"
                aria-label={t.automation.fields.dateTime}
              />
            </div>
          )}
        </div>
      )}

      {/* Webhook Configuration */}
      {trigger.type === 'webhook' && isEdit && trigger.webhook.slug && (
        <WebhookInfo
          slug={trigger.webhook.slug}
          token={trigger.webhook.token}
        />
      )}
      {trigger.type === 'webhook' && !isEdit && (
        <p className="text-muted-foreground text-sm">
          {t.automation.webhook.autoGenerated}
        </p>
      )}

      {/* Heartbeat Configuration */}
      {trigger.type === 'heartbeat' && (
        <div className="space-y-3">
          <div>
            <label className="text-muted-foreground mb-1 block text-xs font-medium">
              {t.automation.fields.intervalMinutes}
            </label>
            <input
              type="number"
              min={1}
              value={Math.round(trigger.heartbeat.intervalMs / 60000)}
              onChange={(e) =>
                onChange({
                  ...trigger,
                  heartbeat: {
                    ...trigger.heartbeat,
                    intervalMs: parseInt(e.target.value, 10) * 60000,
                  },
                })
              }
              className="bg-background text-foreground border-input w-full rounded-md border px-3 py-2 text-sm"
              aria-label={t.automation.fields.interval}
            />
          </div>
          <div>
            <label className="text-muted-foreground mb-1 block text-xs font-medium">
              {t.automation.fields.activeHours}
            </label>
            <input
              type="text"
              placeholder="09:00-17:00"
              value={trigger.heartbeat.activeHours ?? ''}
              onChange={(e) =>
                onChange({
                  ...trigger,
                  heartbeat: {
                    ...trigger.heartbeat,
                    activeHours: e.target.value || undefined,
                  },
                })
              }
              className="bg-background text-foreground border-input w-full rounded-md border px-3 py-2 text-sm"
              aria-label={t.automation.fields.activeHours}
            />
          </div>

          {/* Queue Pickup Settings */}
          <QueuePickupSettings
            heartbeat={trigger.heartbeat}
            onChange={(heartbeat) => onChange({ ...trigger, heartbeat })}
          />
        </div>
      )}

      {/* Manual — no config needed */}
      {trigger.type === 'manual' && (
        <p className="text-muted-foreground text-sm">
          {t.automation.manual.description}
        </p>
      )}
    </div>
  );
}
