/**
 * Media Generation — Provenance Writer
 *
 * Writes generator disclosure directly into persisted media assets so the
 * origin survives even after the file leaves the app. Two strategies:
 *
 *   1. A `<file>.provenance.json` sidecar next to every asset. Independent
 *      of container format, trivially inspectable, and uses the same
 *      field names as a C2PA `stds.schema-org.CreativeWork` assertion so a
 *      future c2pa-node upgrade can adopt the same shape.
 *
 *   2. For PNG files only: inject tEXt chunks (`Software`, `Source`, and a
 *      `Comment` containing the full provenance JSON). PNG tEXt is part of
 *      the PNG spec, read by every image viewer's metadata panel, and can
 *      be re-parsed by this app later for display.
 *
 * No external deps — pure Node implementation, CRC32 table inlined.
 *
 * Intentionally conservative: any write failure is logged and swallowed so
 * media generation itself is never blocked by provenance bookkeeping.
 *
 * @module media-generation/provenance-writer
 */

import { readFile, writeFile } from 'node:fs/promises';

import sharp from 'sharp';

import { createLogger } from '@/shared/utils/logger';

const logger = createLogger('MediaProvenance');

export interface ProvenancePayload {
  /** Actual provider that produced the asset */
  provider: string;
  /** Actual model used */
  model: string;
  /** Requested provider (user setting / explicit call arg) if different */
  requestedProvider?: string;
  /** Requested model if different */
  requestedModel?: string;
  /** Reason for falling back to a different provider */
  fallbackReason?: string;
  /** Seed, for reproducibility */
  seed?: number;
  /** Original prompt, trimmed */
  prompt?: string;
  /** Revised prompt the model actually used, if the provider returned one */
  revisedPrompt?: string;
}

interface SidecarRecord extends ProvenancePayload {
  schema: 'neuma.media.provenance.v1';
  digitalSourceType: 'trainedAlgorithmicMedia';
  generator: string;
  generatedAt: string;
}

const APP_NAME = 'Neuma';

function toSidecar(p: ProvenancePayload): SidecarRecord {
  return {
    schema: 'neuma.media.provenance.v1',
    digitalSourceType: 'trainedAlgorithmicMedia',
    generator: APP_NAME,
    generatedAt: new Date().toISOString(),
    ...p,
  };
}

/**
 * Embed provenance metadata into (or alongside) a freshly persisted media file.
 * Never throws — logs and returns on error.
 *
 * @param sourceBuffer  Optional — the bytes just written to disk. Passing it
 *                      lets the writer skip the readFile round-trip for PNG /
 *                      sharp paths when the caller already has the buffer.
 */
export async function embedProvenance(
  filePath: string,
  payload: ProvenancePayload,
  sourceBuffer?: Buffer,
): Promise<void> {
  const record = toSidecar(payload);

  try {
    await writeFile(
      `${filePath}.provenance.json`,
      JSON.stringify(record, null, 2),
      'utf8',
    );
  } catch (err) {
    logger.warn(
      `Failed to write provenance sidecar for ${filePath}:`,
      err instanceof Error ? err.message : err,
    );
  }

  const lower = filePath.toLowerCase();
  try {
    if (lower.endsWith('.png')) {
      await injectPngProvenance(filePath, record, sourceBuffer);
    } else if (
      lower.endsWith('.jpg') ||
      lower.endsWith('.jpeg') ||
      lower.endsWith('.webp') ||
      lower.endsWith('.tiff') ||
      lower.endsWith('.tif')
    ) {
      await injectSharpExifProvenance(filePath, record, sourceBuffer);
    }
    // .gif/.svg/.mp4/etc. — rely on the sidecar; no universal, lossless
    // in-container path for these formats without a heavy dep.
  } catch (err) {
    logger.warn(
      `Failed to embed provenance into ${filePath}:`,
      err instanceof Error ? err.message : err,
    );
  }
}

// ============================================================================
// EXIF via sharp (JPEG / WebP / TIFF)
// ============================================================================

async function injectSharpExifProvenance(
  filePath: string,
  record: SidecarRecord,
  sourceBuffer?: Buffer,
): Promise<void> {
  const modelTag = record.requestedModel
    ? `${record.model} (requested ${record.requestedModel})`
    : record.model;
  // EXIF ASCII-only tags — strip anything above U+007F to avoid sharp rejecting the write.
  const ascii = (s: string) => s.replace(/[^\x20-\x7e]+/g, ' ').trim();

  const input = sourceBuffer ?? filePath;
  const buf = await sharp(input, { failOn: 'none' })
    .withMetadata({
      exif: {
        IFD0: {
          Software: ascii(`${record.generator} (AI-generated)`),
          Artist: ascii(`${record.provider} — ${modelTag}`),
          ImageDescription: ascii(
            record.fallbackReason
              ? `AI-generated by ${record.provider} after fallback from ${record.requestedProvider}: ${record.fallbackReason}`
              : `AI-generated by ${record.provider} (${record.model})`,
          ),
          Copyright: ascii(`AI-generated — ${record.generator}`),
        },
      },
    })
    .toBuffer();
  await writeFile(filePath, buf);
}

// ============================================================================
// PNG tEXt chunk injection
// ============================================================================

const PNG_SIG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

async function injectPngProvenance(
  filePath: string,
  record: SidecarRecord,
  sourceBuffer?: Buffer,
): Promise<void> {
  const buf = sourceBuffer ?? (await readFile(filePath));
  if (!buf.subarray(0, 8).equals(PNG_SIG)) {
    // Not actually a PNG — skip silently (sidecar already written).
    return;
  }

  const modelTag = record.requestedModel
    ? `${record.generator}/${record.model} (requested ${record.requestedModel})`
    : `${record.generator}/${record.model}`;

  const chunks: Buffer[] = [
    buildTextChunk('Software', `${record.generator} (AI-generated)`),
    buildTextChunk('Source', `${record.provider} — ${modelTag}`),
    buildTextChunk(
      'Comment',
      `AI-generated by ${record.provider} (${record.model}). ` +
        `See ${filePath.split('/').pop()}.provenance.json for full credentials.`,
    ),
    // iTXt for the full JSON — UTF-8 safe, non-compressed.
    buildITextChunk('neuma:provenance', JSON.stringify(record)),
  ];

  // Insert our chunks immediately after IHDR. Per PNG spec: signature (8) then
  // IHDR chunk (first chunk). Length field of IHDR starts at offset 8.
  const ihdrLen = buf.readUInt32BE(8);
  const ihdrEnd = 8 + 4 + 4 + ihdrLen + 4; // len + type + data + crc

  const out = Buffer.concat([
    buf.subarray(0, ihdrEnd),
    ...chunks,
    buf.subarray(ihdrEnd),
  ]);
  await writeFile(filePath, out);
}

function buildTextChunk(keyword: string, text: string): Buffer {
  const data = Buffer.concat([
    Buffer.from(keyword, 'latin1'),
    Buffer.from([0x00]),
    Buffer.from(text, 'latin1'),
  ]);
  return buildChunk('tEXt', data);
}

function buildITextChunk(keyword: string, text: string): Buffer {
  // iTXt: keyword\0 compressionFlag(1) compressionMethod(1) languageTag\0
  //       translatedKeyword\0 utf8Text
  const data = Buffer.concat([
    Buffer.from(keyword, 'latin1'),
    Buffer.from([0x00, 0x00, 0x00]),
    Buffer.from([0x00]), // empty language tag + \0
    Buffer.from([0x00]), // empty translated keyword + \0
    Buffer.from(text, 'utf8'),
  ]);
  return buildChunk('iTXt', data);
}

function buildChunk(type: string, data: Buffer): Buffer {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'latin1');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])) >>> 0, 0);
  return Buffer.concat([len, typeBuf, data, crc]);
}

// CRC-32 (IEEE 802.3 polynomial 0xEDB88320), table-driven. Inlined to avoid a dep.
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf: Buffer): number {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) {
    c = CRC_TABLE[(c ^ buf[i]!) & 0xff]! ^ (c >>> 8);
  }
  return (c ^ 0xffffffff) >>> 0;
}
