export const TEST_SIGNER_WARNING =
  'Development C2PA test signer only. Manifests produced with this signer are untrusted.';

export const TEST_SIGNER_CERT_PEM = [
  '-----BEGIN CERTIFICATE-----',
  'MIIBnjCCAUWgAwIBAgIUDT8kmeW9L+fKGWn+BcF4LDdAOIMwCgYIKoZIzj0EAwIw',
  'JTEjMCEGA1UEAwwaTmV1bWEgQzJQQSBEZXYgVGVzdCBTaWduZXIwHhcNMjYwNTA4',
  'MDI0MjM2WhcNMzYwNTA1MDI0MjM2WjAlMSMwIQYDVQQDDBpOZXVtYSBDMlBBIERl',
  'diBUZXN0IFNpZ25lcjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMyhE6gkLVvo',
  'aGAGu3KmzKS4xzgDBktB6LIWyMiRtWapmriXP5QVMt+lDanChDJrfXtRHIexEPtv',
  '0BcsGFF4IqyjUzBRMB0GA1UdDgQWBBTC+bGAujtpDmYEcmkIXSEKDeS5hTAfBgNV',
  'HSMEGDAWgBTC+bGAujtpDmYEcmkIXSEKDeS5hTAPBgNVHRMBAf8EBTADAQH/MAoG',
  'CCqGSM49BAMCA0cAMEQCICcY6VqwKPAK9JQKLduA0b5UOLwkon02iKjYzltjDrrI',
  'AiBTxH+W2FB3j6b2yCQO62C6fledmh7/lgro+f510tvRwg==',
  '-----END CERTIFICATE-----',
].join('\n');

export const TEST_SIGNER_PRIVATE_KEY_PEM = [
  '-----BEGIN PRIVATE KEY-----',
  'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgR+iJ44U4/1Hy3RPu',
  '2XOQVJXJLvjJRJ1nQdxSGz1Rn8WhRANCAATMoROoJC1b6GhgBrtypsykuMc4AwZL',
  'QeiyFsjIkbVmqZq4lz+UFTLfpQ2pwoQya317URyHsRD7b9AXLBhReCKs',
  '-----END PRIVATE KEY-----',
].join('\n');
